In [30]:
import pandas as pd
df = pd.read_csv('reviews_cronos_score.csv')
df.head(5)

,_id,company,date,opinion,rating,source,sentiment_score,score,rating_user
0,626bd53ad10793287c3acc02,your oxygen,14/02/2015,December 2014 ben ik bij Your Oxygen ingeschre...,4.2,facebook,positive,0.033333,positive
1,626bd53ad10793287c3acc03,ARXUS INC.,29/04/2018,Custom professional IT solutions.,5.0,google,positive,0.100000,positive
2,626bd53ad10793287c3acc04,ARXUS INC.,29/04/2017,Belgian cloud at its best!,5.0,google,positive,1.000000,positive
3,626bd53ad10793287c3acc05,ARXUS INC.,29/04/2018,Fast growing company with motivated people. K...,5.0,google,positive,0.250000,positive
4,626bd53ad10793287c3acc06,ASTENA,2021-10-29,Ok,5.0,google,neutral,0.500000,positive

In [31]:
df['rating'].replace('.',',').astype(float)

0      4.2
1      5.0
2      5.0
3      5.0
4      5.0
5      1.0
6      5.0
7      5.0
8      5.0
9      5.0
10     1.0
11     5.0
12     1.0
13     5.0
14     5.0
15     5.0
16     4.0
17     5.0
18     5.0
19     5.0
20     2.0
21     4.0
22     5.0
23     5.0
24     5.0
25     4.0
26     2.0
27     4.0
28     5.0
29     5.0
30     5.0
31     5.0
32     5.0
33     5.0
34     5.0
35     5.0
36     5.0
37     5.0
38     5.0
39     5.0
40     5.0
41     5.0
42     5.0
43     3.0
44     1.0
45     5.0
46     2.0
47     5.0
48     5.0
49     5.0
50     5.0
51     2.0
52     3.0
53     5.0
54     5.0
55     5.0
56     2.0
57     5.0
58     5.0
59     1.0
60     3.0
61     4.0
62     3.0
63     1.0
64     4.0
65     4.0
66     5.0
67     4.0
68     5.0
69     5.0
70     4.0
71     5.0
72     3.0
73     4.0
74     5.0
75     5.0
76     5.0
77     1.0
78     5.0
79     4.0
80     5.0
81     5.0
82     5.0
83     4.0
84     5.0
85     5.0
86     5.0
87     5.0
88     4.0
89     5.0
90     1.0
91     3.0
92     5.0
93     4.0
94     5.0
95     5.0
96     5.0
97     5.0
98     4.0
99     5.0
100    4.0
101    1.0
102    5.0
103    5.0
104    4.0
105    5.0
106    5.0
107    5.0
108    2.0
109    4.0
110    5.0
111    5.0
112    5.0
113    4.0
114    4.0
115    5.0
116    5.0
117    5.0
118    5.0
119    5.0
120    5.0
121    2.0
122    5.0
123    4.0
124    3.0
125    4.0
126    5.0
127    5.0
128    5.0
129    5.0
130    5.0
131    4.0
132    5.0
133    5.0
134    5.0
135    5.0
136    5.0
137    5.0
138    5.0
139    5.0
140    5.0
141    5.0
142    5.0
143    5.0
144    5.0
145    5.0
146    5.0
147    3.0
148    5.0
149    5.0
150    5.0
151    4.0
152    5.0
153    2.0
154    4.0
155    4.0
156    4.0
157    5.0
158    4.0
159    1.0
160    5.0
161    5.0
162    5.0
163    5.0
164    5.0
165    5.0
166    5.0
167    5.0
168    5.0
169    5.0
170    4.0
171    5.0
172    5.0
173    5.0
174    4.0
175    5.0
176    3.0
177    3.0
178    4.0
179    3.0
180    5.0
181    5.0
182    3.0
183    5.0
184    5.0
185    4.0
186    5.0
187    3.0
188    4.0
189    5.0
190    5.0
191    3.0
192    5.0
193    5.0
194    4.0
195    5.0
196    3.0
197    3.0
198    4.0
199    3.0
200    4.0
201    4.0
202    4.0
203    5.0
204    4.0
205    4.0
206    1.0
207    5.0
208    3.0
209    3.0
210    4.0
211    4.0
212    4.0
213    1.0
214    4.0
215    4.0
216    4.0
217    5.0
218    4.0
219    3.0
220    2.0
221    4.0
222    5.0
223    4.0
224    5.0
225    4.0
226    3.0
227    4.0
228    2.0
229    4.0
230    4.0
231    5.0
232    5.0
233    4.0
234    3.0
235    5.0
236    3.0
237    5.0
238    4.0
239    5.0
240    5.0
241    5.0
242    2.0
243    4.0
244    3.0
245    5.0
246    2.0
247    1.0
248    3.0
249    4.0
250    4.0
251    4.0
252    3.0
253    4.0
254    4.0
255    4.0
256    4.0
257    4.0
258    5.0
259    5.0
260    3.0
261    4.0
262    5.0
263    4.0
264    5.0
265    3.0
266    5.0
267    4.0
268    5.0
269    4.0
270    2.0
271    4.0
272    1.0
273    5.0
274    4.0
275    1.0
276    5.0
277    4.0
278    4.0
279    4.0
280    3.0
281    4.0
282    4.0
283    3.0
284    5.0
285    4.0
286    5.0
287    5.0
288    3.0
289    4.0
290    4.0
291    4.0
292    5.0
293    5.0
294    5.0
295    4.0
296    3.0
297    5.0
298    5.0
299    5.0
300    5.0
301    4.0
302    5.0
303    5.0
304    5.0
305    5.0
306    5.0
307    5.0
308    4.0
309    5.0
310    5.0
311    5.0
312    5.0
313    5.0
314    5.0
315    5.0
316    5.0
317    5.0
318    5.0
319    5.0
320    5.0
321    3.0
322    5.0
323    5.0
324    1.0
325    5.0
326    2.0
327    5.0
328    5.0
329    5.0
330    5.0
331    5.0
332    3.0
333    5.0
334    5.0
335    5.0
336    4.0
337    4.0
338    5.0
339    5.0
340    5.0
341    5.0
342    5.0
343    5.0
344    4.0
345    5.0
346    5.0
347    5.0
348    5.0
349    5.0
350    5.0
351    4.0
352    5.0
353    5.0
354    5.0
355    5.0
356    4.0
357    1.0
358    5.0
359    3.0
360    5.0
361    5.0
362    5.0
363    4.0
364    5.0
365    3.0
366    4.0
367    5.0
368    5.0
369    5.0
370    5.0
371    3.0
372    5.0
373    4.0
374    3.0
375    5.0
376    NaN
377    NaN
378    NaN
379    NaN
Name: rating, dtype: float64

In [28]:
df.dtypes

_id                 object
company             object
date                object
opinion             object
rating             float64
source              object
sentiment_score     object
score              float64
rating_user         object
dtype: object

In [29]:
df.sample(5)

,_id,company,date,opinion,rating,source,sentiment_score,score,rating_user
92,626bd74f2a51ba6a4ed5c50b,HeadCount,03/08/2020,- Trust and good relationships with workers an...,5.0,glassdoor,positive,0.365625,positive
75,626bd74f2a51ba6a4ed5c4fa,Flexso,20/01/2022,Listening box of its super interesting employe...,5.0,glassdoor,positive,0.611111,positive
267,626a963dad878d7a61f7ef13,NaN,21/07/2019,"Good atmosphere, many initiatives for employee...",4.0,glassdoor,positive,0.600000,positive
377,6271024821a1d929e59e45a5,NaN,04/05/2022,That was not the case with my current intermed...,NaN,beyondgaming,negative,-0.130000,negative
44,626bd6de2a51ba6a4ed5c4a6,Cronos International,23/03/2019,"No advantage for this employer, the Helpdesk S...",1.0,glassdoor,negative,-0.225694,negative